package ch.famoser.mensa.services.providers

import android.content.res.AssetManager
import android.net.Uri
import ch.famoser.mensa.models.Location
import ch.famoser.mensa.models.Mensa
import ch.famoser.mensa.models.Menu
import java.util.*
import kotlin.collections.ArrayList
import kotlin.collections.HashMap
import org.jsoup.Jsoup


class UZHMensaProvider(assetManager: AssetManager) : AbstractMensaProvider(assetManager) {
    private val mensaMap: MutableMap<Mensa, UzhMensa> = HashMap()

    fun getMenus(mensa: Mensa, date: Date, language: String): List<Menu> {
        val uzhMensa = mensaMap[mensa]
        if (uzhMensa === null)
            throw IllegalArgumentException("You may only pass objects generated by this provider.")

        try {
            val dayOfWeek = getDayOfWeekForApi(date) ?: return ArrayList()
            val apiUrl = "https://www.mensa.uzh.ch/$language/menueplaene/${uzhMensa.apiUrlSlug}/$dayOfWeek.html"
            val htmlMenus = parseMensaHtml(apiUrl);

            return htmlMenus.map {
                val price = if (it.price != null) it.price!! else arrayOf()
                val title = if (it.title != null) it.title!! else ""
                Menu(title, normalizeText(it.description), price, it.allergenInfo)
            }
        } catch (ex: Exception) {
            ex.printStackTrace()
            return ArrayList()
        }
    }

    private fun getDayOfWeekForApi(date: Date): String? {
        val calender = Calendar.getInstance()
        calender.time = date

        val dayOfWeek = calender.get(Calendar.DAY_OF_WEEK)

        return when (dayOfWeek) {
            Calendar.MONDAY -> "montag"
            Calendar.TUESDAY -> "dienstag"
            Calendar.WEDNESDAY -> "mittwoch"
            Calendar.THURSDAY -> "donnerstag"
            Calendar.FRIDAY -> "freitag"
            else -> null
        };
    }

    private fun parseMensaHtml(url: String): List<HtmlMenu> {
        val doc = Jsoup.connect(url).get()
        val newslistDiv = doc.select("#main .mod-newslist .newslist-description").first()
        val contentDiv = newslistDiv.child(0)

        var currentMenu: HtmlMenu? = null
        val menus = ArrayList<HtmlMenu>()
        for (i in 0 until contentDiv.children().size) {
            val activeChild = contentDiv.child(i);
            if (activeChild.`is`("h3")) {
                val headerText = activeChild.text()
                if (headerText.contains("|")) {
                    if (currentMenu != null) {
                        menus.add(currentMenu)
                    }

                    currentMenu = HtmlMenu()

                    //parse header of the form einfach gut | CHF 5.40 / 7.00 / 10.50
                    val headerParts = headerText.split("|");
                    currentMenu.title = headerParts.get(0).trim()
                    currentMenu.price = headerParts.get(1)
                        .split("/")
                        .map { it.trim('C', 'H', 'F').trim() }
                        .toTypedArray()
                }
            }

            if (activeChild.`is`("p") && currentMenu != null) {
                var paragraphContent = activeChild.textNodes()
                    .joinToString(separator = "\n", transform = { node -> node.wholeText.trim() }).trim()

                if (paragraphContent.startsWith("Allergikerinformationen: ")) {
                    currentMenu.allergenInfo = paragraphContent.substring("Allergikerinformationen: ".length)
                } else {
                    if (currentMenu.description.isNotEmpty()) {
                        currentMenu.description += "\n\n";
                    }

                    if (paragraphContent.contains("Fleisch:")) {
                        paragraphContent = paragraphContent.replace("Fleisch:", "\nFleisch:")
                    }

                    currentMenu.description += paragraphContent
                }
            }
        }

        if (currentMenu != null) {
            menus.add(currentMenu)
        }

        return menus;
    }

    override fun getLocations(): List<Location> {
        val uzhLocations = super.readJsonAssetFileToListOfT("uzh/inventory.json", UzhLocation::class.java);

        return uzhLocations.map { uzhLocation ->
            Location(uzhLocation.title, uzhLocation.mensas.map {
                val mensa = Mensa(
                    UUID.fromString(it.id),
                    it.title,
                    it.mealTime,
                    Uri.parse("http://www.mensa.uzh.ch/de/standorte/${it.infoUrlSlug}.html")
                )
                mensaMap[mensa] = it
                mensa
            })
        }
    }

    private class HtmlMenu {
        var title: String? = null
        var price: Array<String>? = null
        var description: String = ""
        var allergenInfo: String? = null
    }

    private data class UzhLocation(val title: String, val mensas: List<UzhMensa>)
    private data class UzhMensa(
        val id: String,
        val title: String,
        val mealTime: String,
        val apiUrlSlug: String,
        val infoUrlSlug: String
    )
}